{
 "title": "Bots",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Asterios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "asterios x3",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "requests per minute" }
     ],
     "targets": [
      {
       "expr": "increase(asterios_bot_healthcheck_x3[1m])",
       "legendFormat": "parser"
      }
     ]
    },
    {
     "title": "Asterios Bot Users",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id) as \"NEW\\:\"\nFROM user\nWHERE\n  $__timeFilter(created_at)\nORDER BY created_at"
      },
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id) AS \"All Time\\:\"\nFROM user"
      }
     ]
    },
    {
     "title": "Active RB Notification Subscribes",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id) as \"Enabled (All Time)\\:\"\nFROM notification\nWHERE\n  enabled = 1"
      },
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id) as \"All\\:\"\nFROM notification"
      },
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  COALESCE(COUNT(chat_id), 0) as \"New (Enabled)\\:\"\nFROM notification\nWHERE\n  enabled = 1 AND\n  $__timeFilter(created_at)"
      }
     ]
    },
    {
     "title": "asterios x5",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "requests per minute" }
     ],
     "targets": [
      {
       "expr": "increase(asterios_bot_healthcheck_x5[1m])",
       "legendFormat": "parser"
      }
     ]
    },
    {
     "title": "asterios bot usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(asterios_bot_usage[1m])",
       "legendFormat": "usage"
      }
     ]
    },
    {
     "title": "asterios x7",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "requests per minute" }
     ],
     "targets": [
      {
       "expr": "increase(asterios_bot_healthcheck_x7[1m])"
      }
     ]
    },
    {
     "title": "asterios bot notify",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "requests per minute" }
     ],
     "targets": [
      {
       "expr": "increase(asterios_bot_healthcheck_bot_notify[1m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Repeat Word Bot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "New Users",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id) as \"NEW\\:\"\nFROM user\nWHERE\n  $__timeFilter(created_at)\nORDER BY created_at"
      },
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id) AS \"All\\:\"\nFROM user"
      }
     ]
    },
    {
     "title": "Notifications",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 6, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  COALESCE(COUNT(user_id), 0) as \"NEW\\:\"\nFROM learn_notification\nWHERE\n  $__timeFilter(created_at)"
      },
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  COALESCE(COUNT(user_id), 0) as \"Personal\\:\"\nFROM learn_notification_personal"
      },
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  COALESCE(COUNT(user_id), 0) as \"All\\:\"\nFROM learn_notification"
      },
      {
       "rawSql": "SELECT\n  deleted_at AS \"time\",\n  COALESCE(COUNT(user_id), 0) as \"Not found chat\\:\"\nFROM user_notification\nwhere deleted = 1 and\n  $__timeFilter(deleted_at)"
      },
      {
       "rawSql": "SELECT\n  deleted_at AS \"time\",\n  COALESCE(COUNT(user_id), 0) as \"Not found chat (all)\\:\"\nFROM user_notification\nwhere deleted = 1"
      }
     ]
    },
    {
     "title": "Active Users",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  version_notification.created_at AS \"time\",\n  version.version as version,\n  COALESCE(COUNT(version_notification.chat_id), 0) as users\nFROM version_notification\ninner join version ON version.id = version_notification.version_id\ngroup by version.version\norder by version.version desc"
      }
     ]
    },
    {
     "title": "Last Active Users",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT\n  user.updated_at AS \"time\",\n  user.username as UserName,\n  user.first_name as FirstName,\n  user.last_name as LastName,\n  user.id as \"user id\"\nFROM user\nWHERE\n  is_bot = 0 AND\n  $__timeFilter(updated_at)\norder by updated_at desc"
      }
     ]
    },
    {
     "title": "bot usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "requests per minute" }
     ],
     "targets": [
      { "expr": "increase(repeat_bot_usage[1m])" }
     ]
    },
    {
     "title": "export",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "requests per minute" }
     ],
     "targets": [
      {
       "expr": "increase(repeat_bot_export[1m])"
      }
     ]
    },
    {
     "title": "Progress Stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "rawSql": "SELECT \n  count(t.status) as count,\n  t.status,\n  user.username as UserName,\n  user.first_name as FirstName,\n  user.last_name as LastName,\n  user.id as \"user id\"\nFROM `training` as t join user as user on user.id = t.user_id\nwhere t.status != 'never'\ngroup by t.user_id, status\norder by t.status desc, count desc"
      }
     ]
    },
    {
     "title": "worker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "requests per minute" }
     ],
     "targets": [
      {
       "expr": "increase(repeat_bot_worker[1m])"
      }
     ]
    },
    {
     "title": "queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "requests per minute" }
     ],
     "targets": [
      { "expr": "increase(repeat_bot_queue[1m])" }
     ]
    }
   ]
  },
  {
   "title": "Other bots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "currency bot usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "requests per minute" }
     ],
     "targets": [
      {
       "expr": "increase(telegram_bots_usage_currency[1m])"
      }
     ]
    },
    {
     "title": "Currency Bot Users",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id) as \"NEW\\:\"\nFROM user\nWHERE\n  $__timeFilter(created_at)\nORDER BY created_at"
      },
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id) AS \"All Time\\:\"\nFROM user"
      }
     ]
    },
    {
     "title": "Emoji Bot Users",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id) as \"NEW\\:\"\nFROM user\nWHERE\n  $__timeFilter(created_at)\nORDER BY created_at"
      },
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id) AS \"All Time\\:\"\nFROM user"
      }
     ]
    }
   ]
  }
 ]
}